const config = {
  locales: [
    'uk',
    'en'
  ],
  translations: {
    uk: {
      "content-type-builder.plugin.name": "Конструктор",
      "global.back": "Назад",
      "content-manager.components.LeftMenu.collection-types": "Колекція Типів",
      "content-manager.components.LeftMenu.single-types": "Одиночні типи",
      "global.plugins": "Плагіни",
      "global.plugins.content-manager": "Контент Менеджер",
      "app.components.EmptyStateLayout.content-document": "Контент не знайдено",
      "content-manager.HeaderLayout.button.label-add-entry": "Додати новий рядок",
      "content-manager.containers.Edit.information.created": "Створено",
      "Settings.tokens.ListView.headers.createdAt": "Дата створення",
      "Settings.tokens.ListView.headers.lastUsedAt": "Дата редагування",
      "Settings.tokens.ListView.headers.updatedAt": "Дата редагування",
      'Settings.roles.form.permissions.publish': 'Опублікувати',
      'content-manager.containers.Edit.information.draftVersion': 'чорнова версія',
      'content-manager.containers.Edit.information.editing': 'Редагування',
      'content-manager.containers.Edit.information': 'Інформація',
      'app.components.Users.SortPicker.button-label': 'Сортувати за',
      'content-manager.containers.Edit.information.by': 'Ким',
      'content-manager.containers.Edit.information.lastUpdate': 'Останнє оновлення',
      'content-manager.link-to-ctb': 'Редагувати модель',
      'content-manager.header.name': 'Наповнення сайту',
      'app.components.LeftMenu.plugins': 'Плагіни',
      'app.components.LeftMenu.general': 'Загальне',
      'global.marketplace': 'Маркетплейс',
      'global.settings': 'Налаштування',
      'app.utils.published': 'Опубліковано',
      'app.utils.ready-to-publish': 'Готово до Опублікування',
      'global.content-manager': 'Управління контентом',
      'app.components.LeftMenu.navbrand.title': 'Strapi Панель',
      'app.utils.publish': 'Опублікувати',
      'content-manager.components.Select.publish-info-title': 'Стан: Опубліковано',
      'content-manager.bulk-publish.already-published': 'Було Опубліковано',
      'content-manager.containers.List.published': 'Опубліковано',
      'content-manager.components.Select.draft-info-title': 'Стан: Ескіз',
      'content-manager.containers.List.draft': 'Ескіз',
      'content-manager.relation.publicationState.draft': 'Ескіз',  
      'content-manager.containers.Edit.delete-entry': 'Видалити цей тип',
      'app.components.ConfirmDialog.title': 'Підтвердження',
      'content-manager.popUpWarning.warning.has-draft-relations.title': 'Підтвердження', 
      'content-manager.relation.publicationState.published': 'Опубліковано',
      'content-manager.pages.ListView.header-subtitle': '{number, plural, =0 {# entries} один {# entry} інші {# entries}} знайдено',
      'global.actions': 'Дії',
      'global.auditLogs': 'Переглянути логи',
      'global.cancel': 'Відмінити',
      'global.change-password': 'Змінити пароль',
      'global.close': 'Закрити',
      'global.continue': 'Продовжити',
      'global.delete': 'Видалити',
      'global.delete-target': 'Видалити {target}',
      'global.description': 'Опис',
      'global.details': 'Деталі',
      'global.disabled': 'Відключено',
      'global.documentation': 'Документація',
      'global.enabled': 'Увімкнено',
      'global.finish': 'Закінчити',
      'global.name': 'Імя',
      'global.none': 'Пусто',
      'global.password': 'Пароль',
      'global.plugins.content-manager.description': 'Швидкий спосіб побачити, редагувати і видалити дані з бази даних',
      'global.plugins.content-type-builder': 'Конструктор типів',
      'global.plugins.content-type-builder.description': 'Modelize the data structure of your API. Create new fields and relations in just a minute. The files are automatically created and updated in your project.',
      'global.plugins.documentation': 'Документація',
      'global.plugins.documentation.description': 'Create an OpenAPI Document and visualize your API with SWAGGER UI.',
      'global.plugins.email': 'Імейл',
      'global.plugins.email.description': 'Configure your application to send emails.',
      'global.plugins.graphql': 'GraphQL',
      'global.plugins.graphql.description': 'Adds GraphQL endpoint with default API methods.',
      'global.plugins.i18n': 'Internationalization',
      'global.plugins.i18n.description': 'This plugin enables to create, to read and to update content in different languages, both from the Admin Panel and from the API.',
      'global.plugins.sentry': 'Sentry',
      'global.plugins.sentry.description': 'Send Strapi error events to Sentry.',
      'global.plugins.upload': 'Медіа Бібліотека',
      'global.plugins.upload.description': 'Менеджмент медіа файлів',
      'global.plugins.users-permissions': 'Ролі & Доступ',
      'global.plugins.users-permissions.description': 'Protect your API with a full authentication process based on JWT. This plugin comes also with an ACL strategy that allows you to manage the permissions between the groups of users.',
      'global.profile': 'Профіль',
      'global.reset-password': 'Змінити пароль',
      'global.roles': 'Ролі',
      'global.save': 'Зберегти',
      'global.search': 'Пошук',
      'global.see-more': 'Побачити більше',
      'global.select': 'Вибрати',
      'global.select-all-entries': 'Вибрати всі записи',
      'global.type': 'Тип',
      'global.users': 'Користувачі',
      'app.utils.add-filter': 'Добавити фільтер',
      'app.utils.close-label': 'Закрити',
      'app.utils.delete': 'Видалити',
      'app.utils.duplicate': 'Дублювати',
      'app.utils.edit': 'Редагувати',
      'app.utils.errors.file-too-big.message': 'файл завеликий',
      'app.utils.filter-value': 'Фільтрувати значення',
      'app.utils.notify.data-loaded': '{target} загрузжено',
      'app.utils.refresh': 'Оновити',
      'app.utils.select-all': 'Вибрати всі',
      'app.utils.select-field': 'Вибрати поле',
      'app.utils.select-filter': 'Вибрати фільтер',
      'app.utils.unpublish': 'Скасувати публікацію',
      clearLabel: 'Очистити',
      'coming.soon': 'Цей контент під розробкою і буде доступний за декілька тижнів!',
      or: 'Або',
      selectButtonTitle: 'Вибрати',
      skipToContent: 'Перейти до контенту',
      submit: 'Відправити',

      'content-manager.App.schemas.data-loaded': 'Схема була завантажена',
      'content-manager.ListViewTable.relation-loaded': 'Звязки були завантажені',
      'content-manager.ListViewTable.relation-loading': 'Звязки завантажуються',
      'content-manager.ListViewTable.relation-more': 'This relation contains more entities than displayed',
      'content-manager.apiError.This attribute must be unique': '{field} мусть бути унікальним',
      'content-manager.components.DragHandle-label': 'Пересунути',
      'content-manager.components.DraggableCard.delete.field': 'Видалити {item}',
      'content-manager.components.DraggableCard.edit.field': 'Редагувати {item}',
      'content-manager.components.DraggableCard.move.field': 'Посунути {item}',
      'content-manager.components.ListViewTable.row-line': 'елемент {number}',
      'content-manager.components.DynamicZone.ComponentPicker-label': 'Виберіть один компонент',
      'content-manager.components.DynamicZone.add-component': 'Додати компонент до {componentName}',
      'content-manager.components.DynamicZone.delete-label': 'Видалити {name}',
      'content-manager.components.DynamicZone.error-message': 'Компонент містить помилк(у/и)',
      'content-manager.components.DynamicZone.missing-components': 'There {number, plural, =0 {are # missing components} one {is # missing component} other {are # missing components}}',
      'content-manager.components.DynamicZone.move-down-label': 'Пересунути компонент нижче',
      'content-manager.components.DynamicZone.move-up-label': 'Пересунути компонент вверх',
      'content-manager.components.DynamicZone.required': 'Компонент обовязковий',
      'content-manager.components.FieldSelect.label': 'Добавити поле',
      'content-manager.components.Filters.usersSelect.label': 'Знайти і вибрати користувача по якому фільрувати',
      'content-manager.components.LeftMenu.Search.label': 'Знайти контент тип',
      'content-manager.components.NotAllowedInput.text': 'Не має доступу щоб побачити це поле',
      'content-manager.components.RelationInput.icon-button-aria-label': 'Пересунути',
      'content-manager.components.RepeatableComponent.error-message': 'The component(s) contain error(s)',
      'content-manager.components.TableDelete.label': '{number, plural, one {# entry} other {# entries}} selected',
      'content-manager.components.repeatable.reorder.error': "An error occurred while reordering your component's field, please try again",
      'content-manager.containers.Edit.information.publishedVersion': 'Опублікована версія',
      'content-manager.containers.EditView.add.new-entry': 'додати запис',
      'content-manager.containers.ListPage.items': '{number, plural, =0 {items} one {item} other {items}}',
      'content-manager.containers.ListPage.table-headers.publishedAt': 'Стан',
      'content-manager.containers.ListPage.selectedEntriesModal.title': 'Опублікувати записи',
      'content-manager.containers.ListPage.selectedEntriesModal.selectedCount': '<b>{alreadyPublishedCount}</b> {alreadyPublishedCount, plural, =0 {entries} one {entry} other {entries}} already published. <b>{readyToPublishCount}</b> {readyToPublishCount, plural, =0 {entries} one {entry} other {entries}} ready to publish. <b>{withErrorsCount}</b> {withErrorsCount, plural, =0 {entries} one {entry} other {entries}} waiting for action.',
      'content-manager.containers.ListPage.selectedEntriesModal.publishedCount': '<b>{publishedCount}</b> {publishedCount, plural, =0 {entries} one {entry} other {entries}} published. <b>{withErrorsCount}</b> {withErrorsCount, plural, =0 {entries} one {entry} other {entries}} waiting for action.',
      'content-manager.containers.SettingPage.add.relational-field': 'Додати інше суміжне поле',
      'content-manager.containers.SettingPage.editSettings.relation-field.description': 'Set the displayed field in both the edit and list views',
      'content-manager.containers.SettingPage.relations': 'Суміжні поля',
      'content-manager.dnd.cancel-item': '{item}, dropped. Re-order cancelled.',
      'content-manager.dnd.drop-item': '{item}, dropped. Final position in list: {position}.',
      'content-manager.dnd.grab-item': '{item}, grabbed. Current position in list: {position}. Press up and down arrow to change position, Spacebar to drop, Escape to cancel.',
      'content-manager.dnd.instructions': 'Press spacebar to grab and re-order',
      'content-manager.dnd.reorder': '{item}, moved. New position in list: {position}.',
      'content-manager.edit-settings-view.link-to-ctb.components': 'Редагувати компонент',
      'content-manager.edit-settings-view.link-to-ctb.content-types': 'Редагувати контент тип',
      'content-manager.form.Input.hint.character.unit': '{maxValue, plural, one { character} other { characters}}',
      'content-manager.form.Input.hint.minMaxDivider': ' / ',
      'content-manager.form.Input.hint.text': '{min, select, undefined {} other {min. {min}}}{divider}{max, select, undefined {} other {max. {max}}}{unit}{br}{description}',
      'content-manager.form.Input.sort.order': 'Порядок сортування по замовчуванню',
      'content-manager.pages.NoContentType.button': 'Створити свій перший Контент тип',
      'content-manager.pages.NoContentType.text': "You don't have any content yet, we recommend you to create your first Content-Type.",
      'content-manager.permissions.not-allowed.create': 'You are not allowed to create a document',
      'content-manager.permissions.not-allowed.update': 'You are not allowed to see this document',
      'content-manager.popUpWarning.bodyMessage.contentType.publish.all': 'Ви впевнені що хочете опоблікувати ці записи?',
      'content-manager.popUpWarning.bodyMessage.contentType.unpublish.all': 'Ви впевнені що хочете скасувати публікацію цих записів?',
      'content-manager.popUpWarning.warning.publish-question': 'Ви ще хочете опоблікувати?',
      'content-manager.popUpWarning.warning.unpublish': "Якщо ви не опоблікуєте цей контентб він автоматично перейде в Ескіз",
      'content-manager.popUpWarning.warning.unpublish-question': "Ви впевнені що НЕ хочете опоблікувати це?",
      'content-manager.popUpwarning.warning.has-draft-relations.button-confirm': 'Так, опоблікувати',
      'content-manager.popUpwarning.warning.has-draft-relations.message': '<b>{count, plural, one { relation is } other { relations are } }</b> not published yet and might lead to unexpected behavior.',
      'content-manager.popUpwarning.warning.bulk-has-draft-relations.message': '<b>{count} {count, plural, one { relation } other { relations } } out of {entities} { entities, plural, one { entry } other { entries } } {count, plural, one { is } other { are } }</b> not published yet and might lead to unexpected behavior. ',
      'content-manager.popover.display-relations.label': 'Показати відношення',
      'content-manager.relation.add': 'Додати відношення',
      'content-manager.relation.disconnect': 'Видалити',
      'content-manager.relation.isLoading': 'Відношення завантажуються',
      'content-manager.relation.loadMore': 'Завантажити Більше',
      'content-manager.relation.notAvailable': 'Немає доступних відношень',
      'content-manager.reviewWorkflows.stage.label': 'Попередній перегляд',
      'content-manager.select.currently.selected': '{count} зараз вибрано',
      'content-manager.success.record.publish': 'Опубліковано',
      'content-manager.success.record.publishing': 'Опубліковується...',
      'content-manager.success.record.unpublish': 'Забрано з публікації',
      'content-manager.utils.data-loaded': 'The {number, plural, =1 {entry has} other {entries have}} successfully been loaded',
      'content-manager.listView.validation.errors.title': 'Необхідна дія',
      'content-manager.listView.validation.errors.message': 'Please make sure all fields are valid before publishing (required field, min/max character limit, etc.)',


      'components.FilterOptions.FILTER_TYPES.$contains': 'містить',
      'components.FilterOptions.FILTER_TYPES.$containsi': 'містить (case insensitive)',
      'components.FilterOptions.FILTER_TYPES.$endsWith': 'закінчується на',
      'components.FilterOptions.FILTER_TYPES.$endsWithi': 'закінчується на (case insensitive)',
      'components.FilterOptions.FILTER_TYPES.$eq': 'є',
      'components.FilterOptions.FILTER_TYPES.$eqi': 'is (case insensitive)',
      'components.FilterOptions.FILTER_TYPES.$gt': 'є більшим ніж',
      'components.FilterOptions.FILTER_TYPES.$gte': 'є більшим ніж або однаковий',
      'components.FilterOptions.FILTER_TYPES.$lt': 'є маншим ніж',
      'components.FilterOptions.FILTER_TYPES.$lte': 'є меншим ніж або однаковий',
      'components.FilterOptions.FILTER_TYPES.$ne': 'не є',
      'components.FilterOptions.FILTER_TYPES.$nei': 'is not (case insensitive)',
      'components.FilterOptions.FILTER_TYPES.$notContains': 'не містить',
      'components.FilterOptions.FILTER_TYPES.$notContainsi': 'не містить (case insensitive)',
      'components.FilterOptions.FILTER_TYPES.$notNull': 'не є пустим',
      'components.FilterOptions.FILTER_TYPES.$null': 'є пустим',
      'components.FilterOptions.FILTER_TYPES.$startsWith': 'поченається з',
      'components.FilterOptions.FILTER_TYPES.$startsWithi': 'поченається з (case insensitive)',
      'components.Input.error.contain.lowercase': 'пароль має мати хоча б одну букву нижнього регістру',
      'components.Input.error.contain.number': 'пароль має мати хоча б одне число',
      'components.Input.error.contain.uppercase': 'пароль має мати одну букву верхнього регістру',
      'components.Input.error.validation.lowercase': 'значення має містити тільки маленькі літери',
      'components.Input.error.validation.email.withField': '{field} не правильно вказаний імейл',
      'components.Input.error.validation.json.withField': "{field} doesn't match the JSON format",
      'components.Input.error.validation.lowercase.withField': '{field} значення має містити тільки маленькі літери',
      'components.Input.error.validation.max.withField': '{field} is too high.',
      'components.Input.error.validation.maxLength.withField': '{field} is too long.',
      'components.Input.error.validation.min.withField': '{field} is too low.',
      'components.Input.error.validation.minLength.withField': '{field} is too short.',
      'components.Input.error.validation.minSupMax.withField': "{field} can't be superior",
      'components.Input.error.validation.regex.withField': '{field} does not match the regex.',
      'components.Input.error.validation.required.withField': '{field} є обовязковим.',
      'components.Input.error.validation.unique.withField': '{field} уже існує.',
      'components.NotAllowedInput.text': 'No permissions to see this field',
      'components.ViewSettings.tooltip': 'Відкрити налаштування',
      'components.TableHeader.sort': 'сортувати за {label}',
      'components.Blocks.modifiers.bold': 'Жирний',
      'components.Blocks.modifiers.italic': 'Курсив',
      'components.Blocks.modifiers.underline': 'Підкреслення',
      'components.Blocks.modifiers.strikethrough': 'Закреселння',
      'components.Blocks.modifiers.code': 'Код',
      'components.Blocks.link': 'Посилання',
      'components.Blocks.popover.text': 'Текст',
      'components.Blocks.popover.text.placeholder': 'Введіть текст посилання',
      'components.Blocks.popover.link': 'Посилання',
      'components.Blocks.popover.save': 'Зберегти',
      'components.Blocks.popover.cancel': 'Скасувати',
      'components.Blocks.popover.delete': 'Видалити',
      'components.Blocks.popover.edit': 'Редагувати',
      'components.Blocks.blocks.selectBlock': 'Виділити блок',
      'components.Blocks.blocks.text': 'Текст',
      'components.Blocks.blocks.heading1': 'Заголовок 1',
      'components.Blocks.blocks.heading2': 'Заголовок 2',
      'components.Blocks.blocks.heading3': 'Заголовок 3',
      'components.Blocks.blocks.heading4': 'Заголовок 4',
      'components.Blocks.blocks.heading5': 'Заголовок 5',
      'components.Blocks.blocks.heading6': 'Заголовок 6',
      'components.Blocks.blocks.quote': 'Цитата',
      'components.Blocks.blocks.image': 'Картинка',
      'components.Blocks.blocks.unorderedList': 'Маркований список',
      'components.Blocks.blocks.orderedList': 'Нумерований список',
      'components.Wysiwyg.ToggleMode.markdown-mode': 'Режим редагування',
      'components.Wysiwyg.ToggleMode.preview-mode': 'Режим перегляду',
      'components.pagination.go-to': 'Перейти до сторінки {page}',
      'components.pagination.go-to-next': 'Перейти до наступної сторінки',
      'components.pagination.go-to-previous': 'Перейти до попередньої сторінки',
      'components.pagination.remaining-links': 'Додати {number} інших посилання',
      'components.popUpWarning.button.cancel': 'Ні, скасувати',
      'components.popUpWarning.button.confirm': 'Так, підтвердити',

      'app.component.CopyToClipboard.label': 'Копіювати в буфер обміну',
      'app.component.search.label': 'Шукати {target}',
      'app.component.table.duplicate': 'Дублювати {target}',
      'app.component.table.edit': 'Редагувати {target}',
      'app.component.table.read': 'Прочитати {target}',
      'app.component.table.select.one-entry': 'Вибрати {target}',
      'app.component.table.view': '{target} деталі',
      'app.components.BlockLink.blog': 'Блог',
      'app.components.BlockLink.blog.content': 'Read the latest news about Strapi and the ecosystem.',
      'app.components.BlockLink.cloud': 'Strapi Cloud',
      'app.components.BlockLink.cloud.content': 'A fully composable, and collaborative platform to boost your team velocity.',
      'app.components.BlockLink.code.content': 'Learn by testing real projects developed the community.',
      'app.components.BlockLink.documentation.content': 'Discover the essential concepts, guides and instructions.',
      'app.components.BlockLink.tutorial': 'Tutorials',
      'app.components.BlockLink.tutorial.content': 'Follow step-by-step instructions to use and customize Strapi.',
      'app.components.Button.confirm': 'Підтвердити',
      'app.components.EmptyStateLayout.content-permissions': "You don't have the permissions to access that content",
      'app.components.GuidedTour.CM.create.content': "<p>Create and manage all the content here in the Content Manager.</p><p>Ex: Taking the Blog website example further, one can write an Article, save and publish it as they like.</p><p>💡 Quick tip — Don't forget to hit publish on the content you create.</p>",
      'app.components.GuidedTour.CM.create.title': '⚡️ Create content',
      'app.components.GuidedTour.CM.success.content': '<p>Awesome, one last step to go!</p><b>🚀 See content in action</b>',
      'app.components.GuidedTour.CM.success.cta.title': 'Test the API',
      'app.components.GuidedTour.CM.success.title': 'Step 2: Completed ✅',
      'app.components.GuidedTour.CTB.create.content': '<p>Collection Types help you manage several entries, Single Types are suitable to manage only one entry.</p> <p>Ex: For a Blog website, Articles would be a Collection Type whereas a Homepage would be a Single Type.</p>',
      'app.components.GuidedTour.CTB.create.cta.title': 'Build a Collection Type',
      'app.components.GuidedTour.CTB.create.title': '🧠 Create a first Collection Type',
      'app.components.GuidedTour.CTB.success.content': '<p>Good going!</p><b>⚡️ What would you like to share with the world?</b>',
      'app.components.GuidedTour.CTB.success.title': 'Step 1: Completed ✅',
      'app.components.GuidedTour.apiTokens.create.content': '<p>Generate an authentication token here and retrieve the content you just created.</p>',
      'app.components.GuidedTour.apiTokens.create.cta.title': 'Generate an API Token',
      'app.components.GuidedTour.apiTokens.create.title': '🚀 See content in action',
      'app.components.GuidedTour.apiTokens.success.content': "<p>See content in action by making an HTTP request:</p><ul><li><p>To this URL: <light>https://'<'YOUR_DOMAIN'>'/api/'<'YOUR_CT'>'</light></p></li><li><p>With the header: <light>Authorization: bearer '<'YOUR_API_TOKEN'>'</light></p></li></ul><p>For more ways to interact with content, see the <documentationLink>documentation</documentationLink>.</p>",
      'app.components.GuidedTour.apiTokens.success.cta.title': 'Go back to homepage',
      'app.components.GuidedTour.apiTokens.success.title': 'Step 3: Completed ✅',
      'app.components.GuidedTour.create-content': 'Create content',
      'app.components.GuidedTour.home.CM.title': '⚡️ What would you like to share with the world?',
      'app.components.GuidedTour.home.CTB.cta.title': 'Go to the Content type Builder',
      'app.components.GuidedTour.home.CTB.title': '🧠 Build the content structure',
      'app.components.GuidedTour.home.apiTokens.cta.title': 'Test the API',
      'app.components.GuidedTour.skip': 'Skip the tour',
      'app.components.GuidedTour.title': '3 steps to get started',
      'app.components.HomePage.roadmap': 'See our roadmap',
      'app.components.LeftMenu.collapse': 'Сховати панель',
      'app.components.LeftMenu.expand': 'Відкрити панель',
      'app.components.LeftMenu.logo.alt': 'Application logo',
      'app.components.LeftMenu.logout': 'Розлогінитись',
      'app.components.LeftMenu.navbrand.workplace': 'Workplace',
      'app.components.ListPluginsPage.deletePlugin.description': 'It might take a few seconds to uninstall the plugin.',
      'app.components.ListPluginsPage.deletePlugin.title': 'Uninstalling',
      'app.components.MarketplaceBanner': 'Discover plugins built by the community, and many more awesome things to kickstart your project, on Strapi Marketplace.',
      'app.components.MarketplaceBanner.image.alt': 'A Strapi rocket logo',
      'app.components.MarketplaceBanner.link': 'Check it out now',
      'app.components.NpsSurvey.banner-title': 'How likely are you to recommend Strapi to a friend or colleague?',
      'app.components.NpsSurvey.feedback-response': 'Thank you very much for your feedback!',
      'app.components.NpsSurvey.feedback-question': 'Do you have any suggestion for improvements?',
      'app.components.NpsSurvey.submit-feedback': 'Submit Feedback',
      'app.components.NpsSurvey.dismiss-survey-label': 'Dismiss survey',
      'app.components.NpsSurvey.no-recommendation': 'Not at all likely',
      'app.components.NpsSurvey.happy-to-recommend': 'Extremely likely',
      'app.components.Onboarding.help.button': 'Help button',
      'app.components.Onboarding.link.build-content': 'Build a content architecture',
      'app.components.Onboarding.link.manage-content': 'Add & manage content',
      'app.components.Onboarding.link.manage-media': 'Manage media',
      'app.components.Onboarding.link.more-videos': 'Watch more videos',
      'app.components.ToggleCheckbox.off-label': 'Ні',
      'app.components.ToggleCheckbox.on-label': 'Так',
      'app.components.Users.MagicLink.connect': 'Copy and share this link to give access to this user',
      'app.components.Users.MagicLink.connect.sso': 'Send this link to the user, the first login can be made via a SSO provider',
      'app.components.Users.ModalCreateBody.block-title.details': 'Деталі користувача',
      'app.components.Users.ModalCreateBody.block-title.roles': "Ролі користувача",
      'app.components.Users.ModalCreateBody.block-title.roles.description': 'A user can have one or several roles',
      'app.components.Users.SortPicker.sortby.email_asc': 'Email (А до Я)',
      'app.components.Users.SortPicker.sortby.email_desc': 'Email (Я до A)',
      'app.components.Users.SortPicker.sortby.firstname_asc': 'Імя (A до Я)',
      'app.components.Users.SortPicker.sortby.firstname_desc': 'Імя (Я до A)',
      'app.components.Users.SortPicker.sortby.lastname_asc': 'Прізвище (A до Я)',
      'app.components.Users.SortPicker.sortby.lastname_desc': 'Прізвище (Я до A)',
      'app.components.Users.SortPicker.sortby.username_asc': 'Username (A to Z)',
      'app.components.Users.SortPicker.sortby.username_desc': 'Username (Z to A)',
  
    }
  }
};

const missingTranslations =  {
    'Auth.components.Oops.text': 'Your account has been suspended.',
    'Auth.components.Oops.text.admin': 'If this is a mistake, please contact your administrator.',
    'Auth.components.Oops.title': 'Oops...',
    'Auth.form.active.label': 'Active',
    'Auth.form.button.go-home': 'GO BACK HOME',
    'Auth.form.button.login.providers.error': 'We cannot connect you through the selected provider.',
    'Auth.form.button.login.strapi': 'Log in via Strapi',
    'Auth.form.button.password-recovery': 'Password Recovery',
    'Auth.form.confirmPassword.label': 'Confirm Password',
    'Auth.form.currentPassword.label': 'Current Password',
    'Auth.form.email.label': 'Email',
    'Auth.form.email.placeholder': 'e.g. kai@doe.com',
    'Auth.form.firstname.label': 'First name',
    'Auth.form.firstname.placeholder': 'e.g. Kai',
    'Auth.form.lastname.label': 'Last name',
    'Auth.form.lastname.placeholder': 'e.g. Doe',
    'Auth.form.password.hide-password': 'Hide password',
    'Auth.form.password.hint': 'Must be at least 8 characters, 1 uppercase, 1 lowercase & 1 number',
    'Auth.form.password.show-password': 'Show password',
    'Auth.form.register.subtitle': 'Credentials are only used to authenticate in Strapi. All saved data will be stored in your database.',
    'Auth.form.rememberMe.label': 'Remember me',
    'Auth.form.username.label': 'Username',
    'Auth.form.username.placeholder': 'e.g. Kai_Doe',
    'Auth.form.welcome.subtitle': 'Log in to your Strapi account',
    'Auth.form.welcome.title': 'Welcome to Strapi!',
    'Auth.link.signin': 'Sign in',
    'Auth.link.signin.account': 'Already have an account?',
    'Auth.login.sso.divider': 'Or login with',
    'Auth.login.sso.loading': 'Loading providers...',
    'Auth.login.sso.subtitle': 'Login to your account via SSO',
    'Auth.reset-password.title': 'Reset password',

    'Roles.ListPage.notification.delete-all-not-allowed': 'Some roles could not be deleted since they are associated with users',
    'Roles.ListPage.notification.delete-not-allowed': 'A role cannot be deleted if associated with users',
    'Roles.RoleRow.select-all': 'Select {name} for bulk actions',
    'Roles.RoleRow.user-count': '{number, plural, =0 {# user} one {# user} other {# users}}',
    'Roles.components.List.empty.withSearch': 'There is no role corresponding to the search ({search})...',

    'Settings.PageTitle': 'Settings — {name}',
    'Settings.apiTokens.ListView.headers.createdAt': 'Created at',
    'Settings.apiTokens.ListView.headers.description': 'Description',
    'Settings.apiTokens.ListView.headers.lastUsedAt': 'Last used',
    'Settings.apiTokens.ListView.headers.name': 'Name',
    'Settings.apiTokens.ListView.headers.type': 'Token type',
    'Settings.apiTokens.addFirstToken': 'Add your first API Token',
    'Settings.apiTokens.addNewToken': 'Add new API Token',
    'Settings.apiTokens.create': 'Create new API Token',
    'Settings.apiTokens.createPage.BoundRoute.title': 'Bound route to',
    'Settings.apiTokens.createPage.permissions.description': 'Only actions bound by a route are listed below.',
    'Settings.apiTokens.createPage.permissions.header.hint': "Select the application's actions or the plugin's actions and click on the cog icon to display the bound route",
    'Settings.apiTokens.createPage.permissions.header.title': 'Advanced settings',
    'Settings.apiTokens.createPage.permissions.title': 'Permissions',
    'Settings.apiTokens.createPage.title': 'Create API Token',
    'Settings.apiTokens.description': 'List of generated tokens to consume the API',
    'Settings.apiTokens.emptyStateLayout': 'You don’t have any content yet...',
    'Settings.apiTokens.regenerate': 'Regenerate',
    'Settings.apiTokens.title': 'API Tokens',
    'Settings.apiTokens.lastHour': 'last hour',
    'Settings.application.customization': 'Customization',
    'Settings.application.customization.auth-logo.carousel-hint': 'Replace the logo in the authentication pages',
    'Settings.application.customization.carousel-hint': 'Change the admin panel logo (Max dimension: {dimension}x{dimension}, Max file size: {size}KB)',
    'Settings.application.customization.carousel-slide.label': 'Logo slide',
    'Settings.application.customization.carousel.auth-logo.title': 'Auth logo',
    'Settings.application.customization.carousel.change-action': 'Change logo',
    'Settings.application.customization.carousel.menu-logo.title': 'Menu logo',
    'Settings.application.customization.carousel.reset-action': 'Reset logo',
    'Settings.application.customization.carousel.title': 'Logo',
    'Settings.application.customization.menu-logo.carousel-hint': 'Replace the logo in the main navigation',
    'Settings.application.customization.modal.cancel': 'Cancel',
    'Settings.application.customization.modal.pending': 'Pending logo',
    'Settings.application.customization.modal.pending.card-badge': 'image',
    'Settings.application.customization.modal.pending.choose-another': 'Choose another logo',
    'Settings.application.customization.modal.pending.subtitle': 'Manage the chosen logo before uploading it',
    'Settings.application.customization.modal.pending.title': 'Logo ready to upload',
    'Settings.application.customization.modal.pending.upload': 'Upload logo',
    'Settings.application.customization.modal.tab.label': 'How do you want to upload your assets?',
    'Settings.application.customization.modal.upload': 'Upload logo',
    'Settings.application.customization.modal.upload.cta.browse': 'Browse files',
    'Settings.application.customization.modal.upload.drag-drop': 'Drag and Drop here or',
    'Settings.application.customization.modal.upload.error-format': 'Wrong format uploaded (accepted formats only: jpeg, jpg, png, svg).',
    'Settings.application.customization.modal.upload.error-network': 'Network error',
    'Settings.application.customization.modal.upload.error-size': 'The file uploaded is too large (max dimension: {dimension}x{dimension}, max file size: {size}KB)',
    'Settings.application.customization.modal.upload.file-validation': 'Max dimension: {dimension}x{dimension}, Max size: {size}KB',
    'Settings.application.customization.modal.upload.from-computer': 'From computer',
    'Settings.application.customization.modal.upload.from-url': 'From URL',
    'Settings.application.customization.modal.upload.from-url.input-label': 'URL',
    'Settings.application.customization.modal.upload.next': 'Next',
    'Settings.application.customization.size-details': 'Max dimension: {dimension}×{dimension}, Max file size: {size}KB',
    'Settings.application.description': 'Administration panel’s global information',
    'Settings.application.edition-title': 'current plan',
    'Settings.application.ee-or-ce': '{communityEdition, select, true {Community Edition} other {Enterprise Edition}}',
    'Settings.application.ee.admin-seats.add-seats': '{isHostedOnStrapiCloud, select, true {Add seats} other {Contact sales}}',
    'Settings.application.ee.admin-seats.at-limit-tooltip': 'At limit: add seats to invite more users',
    'Settings.application.ee.admin-seats.count': '<text>{enforcementUserCount}</text>/{permittedSeats}',
    'Settings.application.get-help': 'Get help',
    'Settings.application.link-pricing': 'See all pricing plans',
    'Settings.application.link-upgrade': 'Upgrade your admin panel',
    'Settings.application.node-version': 'node version',
    'Settings.application.strapi-version': 'Strapi version',
    'Settings.application.strapiVersion': 'Strapi version',
    'Settings.application.title': 'Overview',
    'Settings.permissions': 'Administration panel',
    'Settings.permissions.auditLogs.action': 'Action',
    'Settings.permissions.auditLogs.admin.auth.success': 'Admin login',
    'Settings.permissions.auditLogs.admin.logout': 'Admin logout',
    'Settings.permissions.auditLogs.component.create': 'Create component',
    'Settings.permissions.auditLogs.component.delete': 'Delete component',
    'Settings.permissions.auditLogs.component.update': 'Update component',
    'Settings.permissions.auditLogs.content-type.create': 'Create content type',
    'Settings.permissions.auditLogs.content-type.delete': 'Delete content type',
    'Settings.permissions.auditLogs.content-type.update': 'Update content type',
    'Settings.permissions.auditLogs.date': 'Date',
    'Settings.permissions.auditLogs.details': 'Log Details',
    'Settings.permissions.auditLogs.entry.create': 'Create entry{model, select, undefined {} other { ({model})}}',
    'Settings.permissions.auditLogs.entry.delete': 'Delete entry{model, select, undefined {} other { ({model})}}',
    'Settings.permissions.auditLogs.entry.publish': 'Publish entry {model, select, undefined {} other {({model})}}',
    'Settings.permissions.auditLogs.entry.unpublish': 'Unpublish entry{model, select, undefined {} other { ({model})}}',
    'Settings.permissions.auditLogs.entry.update': 'Update entry{model, select, undefined {} other { ({model})}}',
    'Settings.permissions.auditLogs.filters.combobox.aria-label': 'Search and select an option to filter',
    'Settings.permissions.auditLogs.listview.header.subtitle': 'Logs of all the activities that happened in your environment',
    'Settings.permissions.auditLogs.media.create': 'Create media',
    'Settings.permissions.auditLogs.media.delete': 'Delete media',
    'Settings.permissions.auditLogs.media.update': 'Update media',
    'Settings.permissions.auditLogs.payload': 'Payload',
    'Settings.permissions.auditLogs.permission.create': 'Create permission',
    'Settings.permissions.auditLogs.permission.delete': 'Delete permission',
    'Settings.permissions.auditLogs.permission.update': 'Update permission',
    'Settings.permissions.auditLogs.role.create': 'Create role',
    'Settings.permissions.auditLogs.role.delete': 'Delete role',
    'Settings.permissions.auditLogs.role.update': 'Update role',
    'Settings.permissions.auditLogs.user': 'User',
    'Settings.permissions.auditLogs.user.create': 'Create user',
    'Settings.permissions.auditLogs.user.delete': 'Delete user',
    'Settings.permissions.auditLogs.user.fullname': '{firstname} {lastname}',
    'Settings.permissions.auditLogs.user.update': 'Update user',
    'Settings.permissions.auditLogs.userId': 'User ID',
    'Settings.permissions.category': 'Permissions settings for the {category}',
    'Settings.permissions.category.plugins': 'Permissions settings for the {category} plugin',
    'Settings.permissions.conditions.anytime': 'Anytime',
    'Settings.permissions.conditions.apply': 'Apply',
    'Settings.permissions.conditions.can': 'Can',
    'Settings.permissions.conditions.conditions': 'Conditions',
    'Settings.permissions.conditions.define-conditions': 'Define conditions',
    'Settings.permissions.conditions.links': 'Links',
    'Settings.permissions.conditions.no-actions': 'You first need to select actions (create, read, update, ...) before defining conditions on them.',
    'Settings.permissions.conditions.none-selected': 'Anytime',
    'Settings.permissions.conditions.or': 'OR',
    'Settings.permissions.conditions.when': 'When',
    'Settings.permissions.select-all-by-permission': 'Select all {label} permissions',
    'Settings.permissions.select-by-permission': 'Select {label} permission',
    'Settings.permissions.users.active': 'Active',
    'Settings.permissions.users.create': 'Invite new user',
    'Settings.permissions.users.email': 'Email',
    'Settings.permissions.users.firstname': 'Firstname',
    'Settings.permissions.users.form.sso': 'Connect with SSO',
    'Settings.permissions.users.sso.provider.error': 'An error occurred while requesting the SSO settings',
    'Settings.permissions.users.form.sso.description': 'When enabled (ON), users can login via SSO',
    'Settings.permissions.users.inactive': 'Inactive',
    'Settings.permissions.users.lastname': 'Lastname',
    'Settings.permissions.users.listview.header.subtitle': 'All the users who have access to the Strapi admin panel',
    'Settings.permissions.users.roles': 'Roles',
    'Settings.permissions.users.strapi-author': 'Author',
    'Settings.permissions.users.strapi-editor': 'Editor',
    'Settings.permissions.users.strapi-super-admin': 'Super Admin',
    'Settings.permissions.users.tabs.label': 'Tabs Permissions',
    'Settings.permissions.users.user-status': 'User status',
    'Settings.permissions.users.username': 'Username',
    'Settings.profile.form.notify.data.loaded': 'Your profile data has been loaded',
    'Settings.profile.form.section.experience.clear.select': 'Clear the interface language selected',
    'Settings.profile.form.section.experience.here': 'here',
    'Settings.profile.form.section.experience.interfaceLanguage': 'Interface language',
    'Settings.profile.form.section.experience.interfaceLanguage.hint': 'This will only display your own interface in the chosen language.',
    'Settings.profile.form.section.experience.interfaceLanguageHelp': 'Preference changes will apply only to you. More information is available {here}.',
    'Settings.profile.form.section.experience.mode.hint': 'Displays your interface in the chosen mode.',
    'Settings.profile.form.section.experience.mode.label': 'Interface mode',
    'Settings.profile.form.section.experience.mode.option-label': '{name} mode',
    'Settings.profile.form.section.experience.title': 'Experience',
    'Settings.profile.form.section.helmet.title': 'User profile',
    'Settings.profile.form.section.profile.page.title': 'Profile page',
    'Settings.review-workflows.page.title': 'Review Workflows',
    'Settings.review-workflows.page.subtitle': '{count, plural, one {# stage} other {# stages}}',
    'Settings.review-workflows.page.isLoading': 'Workflow is loading',
    'Settings.review-workflows.page.delete.confirm.body': 'All entries assigned to deleted stages will be moved to the previous stage. Are you sure you want to save?',
    'Settings.review-workflows.stage.name.label': 'Stage name',
    'Settings.roles.create.description': 'Define the rights given to the role',
    'Settings.roles.create.title': 'Create a role',
    'Settings.roles.created': 'Role created',
    'Settings.roles.edit.title': 'Edit a role',
    'Settings.roles.form.button.users-with-role': '{number, plural, =0 {# users} one {# user} other {# users}} with this role',
    'Settings.roles.form.created': 'Created',
    'Settings.roles.form.description': 'Name and description of the role',
    'Settings.roles.form.permission.property-label': '{label} permissions',
    'Settings.roles.form.permissions.attributesPermissions': 'Fields permissions',
    'Settings.roles.form.permissions.create': 'Create',
    'Settings.roles.form.permissions.delete': 'Delete',
    'Settings.roles.form.permissions.read': 'Read',
    'Settings.roles.form.permissions.update': 'Update',
    'Settings.roles.list.button.add': 'Add new role',
    'Settings.roles.list.description': 'List of roles',
    'Settings.roles.title.singular': 'role',
    'Settings.sso.description': 'Configure the settings for the Single Sign-On feature.',
    'Settings.sso.form.defaultRole.description': 'It will attach the new authenticated user to the selected role',
    'Settings.sso.form.defaultRole.description-not-allowed': 'You need to have the permission to read the admin roles',
    'Settings.sso.form.defaultRole.label': 'Default role',
    'Settings.sso.form.localAuthenticationLock.label': 'Local authentication lock-out',
    'Settings.sso.form.localAuthenticationLock.description': 'Select the roles for which you want to disable the local authentication',
    'Settings.sso.form.registration.description': 'Create new user on SSO login if no account exists',
    'Settings.sso.form.registration.label': 'Auto-registration',
    'Settings.sso.title': 'Single Sign-On',
    'Settings.tokens.Button.cancel': 'Cancel',
    'Settings.tokens.Button.regenerate': 'Regenerate',
    'Settings.tokens.ListView.headers.createdAt': 'Created at',
    'Settings.tokens.ListView.headers.description': 'Description',
    'Settings.tokens.ListView.headers.lastUsedAt': 'Last used',
    'Settings.tokens.ListView.headers.name': 'Name',
    'Settings.tokens.RegenerateDialog.title': 'Regenerate token',
    'Settings.tokens.copy.editMessage': 'For security reasons, you can only see your token once.',
    'Settings.tokens.copy.editTitle': 'This token isn’t accessible anymore.',
    'Settings.tokens.copy.lastWarning': 'Make sure to copy this token, you won’t be able to see it again!',
    'Settings.tokens.duration.30-days': '30 days',
    'Settings.tokens.duration.7-days': '7 days',
    'Settings.tokens.duration.90-days': '90 days',
    'Settings.tokens.duration.expiration-date': 'Expiration date',
    'Settings.tokens.duration.unlimited': 'Unlimited',
    'Settings.tokens.form.description': 'Description',
    'Settings.tokens.form.duration': 'Token duration',
    'Settings.tokens.form.name': 'Name',
    'Settings.tokens.form.type': 'Token type',
    'Settings.tokens.notification.copied': 'Token copied to clipboard.',
    'Settings.tokens.popUpWarning.message': 'Are you sure you want to regenerate this token?',
    'Settings.tokens.regenerate': 'Regenerate',
    'Settings.tokens.types.custom': 'Custom',
    'Settings.tokens.types.full-access': 'Full access',
    'Settings.tokens.types.read-only': 'Read-only',
    'Settings.transferTokens.ListView.headers.type': 'Token type',
    'Settings.transferTokens.addFirstToken': 'Add your first Transfer Token',
    'Settings.transferTokens.addNewToken': 'Add new Transfer Token',
    'Settings.transferTokens.create': 'Create new Transfer Token',
    'Settings.transferTokens.createPage.title': 'Create Transfer Token',
    'Settings.transferTokens.description': 'List of generated transfer tokens',
    'Settings.transferTokens.emptyStateLayout': 'You don’t have any content yet...',
    'Settings.transferTokens.title': 'Transfer Tokens',
    'Settings.webhooks.event.publish-tooltip': 'This event only exists for contents with Draft/Publish system enabled',
    'Settings.webhooks.event.select': 'Select event',
    'Settings.webhooks.events.isLoading': 'Events loading',
    'Settings.webhooks.events.update': 'Update',
    'Settings.webhooks.events.delete': 'Delete webhook',
    'Settings.webhooks.headers.remove': 'Remove header row {number}',
    'Settings.webhooks.list.th.actions': 'actions',
    'Settings.webhooks.list.th.status': 'status',
    'Settings.webhooks.list.loading.success': 'Webhooks have been loaded',
    'Settings.webhooks.to.delete': '{webhooksToDeleteLength, plural, one {# webhook} other {# webhooks}} selected',
    'Settings.webhooks.validation.name.required': 'Name is required',
    'Settings.webhooks.validation.name.regex': 'The name must start with a letter and only contain letters, numbers, spaces and underscores',
    'Settings.webhooks.validation.url.required': 'Url is required',
    'Settings.webhooks.validation.url.regex': 'The value must be a valid Url',
    'Settings.webhooks.validation.key': 'Key is required',
    'Settings.webhooks.validation.value': 'Value is required',

    'Usecase.back-end': 'Back-end developer',
    'Usecase.button.skip': 'Skip this question',
    'Usecase.content-creator': 'Content Creator',
    'Usecase.front-end': 'Front-end developer',
    'Usecase.full-stack': 'Full-stack developer',
    'Usecase.input.work-type': 'What type of work do you do?',
    'Usecase.notification.success.project-created': 'Project has been successfully created',
    'Usecase.other': 'Other',
    'Usecase.title': 'Tell us a bit more about yourself',

    'Users.components.List.empty': 'There is no users...',
    'Users.components.List.empty.withFilters': 'There is no users with the applied filters...',
    'Users.components.List.empty.withSearch': 'There is no users corresponding to the search ({search})...',

    anErrorOccurred: 'Woops! Something went wrong. Please, try again.',

 
    'app.containers.AuthPage.ForgotPasswordSuccess.text.contact-admin': 'If you do not receive this link, please contact your administrator.',
    'app.containers.AuthPage.ForgotPasswordSuccess.text.email': 'It can take a few minutes to receive your password recovery link.',
    'app.containers.AuthPage.ForgotPasswordSuccess.title': 'Email sent',
    'app.containers.Users.EditPage.form.active.label': 'Active',
    'app.containers.Users.EditPage.header.label': 'Edit {name}',
    'app.containers.Users.EditPage.header.label-loading': 'Edit user',
    'app.containers.Users.EditPage.roles-bloc-title': 'Attributed roles',
    'app.containers.Users.ModalForm.footer.button-success': 'Invite user',

    'app.page.not.found': "Oops! We can't seem to find the page you're looking for...",

    'app.static.links.cheatsheet': 'CheatSheet',


   

    dark: 'Dark',

    'form.button.continue': 'Continue',

    'global.fullname': '{firstname} {lastname}',

    light: 'Light',
    
    'notification.default.title': 'Information:',
    'notification.ee.warning.at-seat-limit.title': '{licenseLimitStatus, select, OVER_LIMIT {Over} AT_LIMIT {At}} seat limit ({currentUserCount}/{permittedSeats})',
    'notification.ee.warning.over-.message': "Add seats to {licenseLimitStatus, select, OVER_LIMIT {invite} AT_LIMIT {re-enable}} Users. If you already did it but it's not reflected in Strapi yet, make sure to restart your app.",
    'notification.error.invalid.configuration': 'You have an invalid configuration, check your server log for more information.',
    'notification.error.tokennamenotunique': 'Name already assigned to another token',
    'notification.link-copied': 'Link copied into the clipboard',
    'notification.permission.not-allowed-read': 'You are not allowed to see this document',
    'notification.success.apitokencreated': 'API Token successfully created',
    'notification.success.apitokenedited': 'API Token successfully edited',
    'notification.success.saved': 'Saved',
    'notification.success.title': 'Success:',
    'notification.success.transfertokencreated': 'Transfer Token successfully created',
    'notification.success.transfertokenedited': 'Transfer Token successfully edited',
    'notification.version.update.message': 'A new version of Strapi is available!',
    'notification.warning.404': '404 - Not found',
    'notification.warning.title': 'Warning:',
}

const bootstrap = (app) => {
  console.log(app);
};

export default {
  config,
  bootstrap,
};
